// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd290j39-N7XdWkdrrHlvKTBE-OTaevf8',
    appId: '1:305906840427:web:dba5363a25aaa46988d22e',
    messagingSenderId: '305906840427',
    projectId: 'flutter-62f7f',
    authDomain: 'flutter-62f7f.firebaseapp.com',
    storageBucket: 'flutter-62f7f.appspot.com',
    measurementId: 'G-RTPYVPDS0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3AvP4IIYKTH_Gvxvx55_A9OjunnjNZyY',
    appId: '1:305906840427:android:2f306938a6b23b0c88d22e',
    messagingSenderId: '305906840427',
    projectId: 'flutter-62f7f',
    storageBucket: 'flutter-62f7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0xiTCeUsRst1blAVTU2EpTBC5f0NTFs',
    appId: '1:305906840427:ios:78bb7aba949be21d88d22e',
    messagingSenderId: '305906840427',
    projectId: 'flutter-62f7f',
    storageBucket: 'flutter-62f7f.appspot.com',
    iosClientId: '305906840427-79ogeob93e1d8cc8jb2q7837pnf75hlo.apps.googleusercontent.com',
    iosBundleId: 'com.madebybriandang.flutterapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr0xiTCeUsRst1blAVTU2EpTBC5f0NTFs',
    appId: '1:305906840427:ios:78bb7aba949be21d88d22e',
    messagingSenderId: '305906840427',
    projectId: 'flutter-62f7f',
    storageBucket: 'flutter-62f7f.appspot.com',
    iosClientId: '305906840427-79ogeob93e1d8cc8jb2q7837pnf75hlo.apps.googleusercontent.com',
    iosBundleId: 'com.madebybriandang.flutterapps',
  );
}
